version: '3'

services:
  saas-api:
    image: saas-api
    pull_policy: never
    restart: always
    container_name: saas-api
    environment:
      DATABASE_HOST: ${POSTGRES_HOST}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.saas-api.entrypoints=http"
      - "traefik.http.routers.saas-api.rule=Host(`api.saas.thiagosol.com`)"
      - "traefik.http.routers.saas-api-secure.entrypoints=https"
      - "traefik.http.routers.saas-api-secure.rule=Host(`api.saas.thiagosol.com`)"
      - "traefik.http.routers.saas-api-secure.tls=true"
      - "traefik.http.routers.saas-api-secure.service=saas-api-secure"
      - "traefik.http.services.saas-api-secure.loadbalancer.server.port=8080"
      - "traefik.docker.network=external-sol-apis"
    networks:
      - external-sol-apis
      - logging-network
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=saas-api,type=service"
        loki-retries: "5"
        loki-batch-size: "400"
        mode: "non-blocking"
    deploy:
      resources:
        limits:
          memory: 100M

networks:
  logging-network:
    external: true
  external-sol-apis:
    external: true
